### ISSUE TITLE
fix(derive): a derive in a function body cannot resolve its own types through `super`

### ISSUE THREAD

**Issue by jdx** [jdx/usage#935]
A `Cli`, `Args`, or `Subcommands` derive on a type declared inside a function body does not compile:

```rust
fn main() {
    #[derive(Args)]
    struct Inner { #[usage(long)] thing: bool }
    #[derive(Subcommands)]
    enum Local { /// Wrapping
        Inner(Inner) }
    #[derive(Cli)]
    #[usage(bin = "lo")]
    struct Lo { #[usage(subcommand)] command: Option<Local> }
    println!("{}", Lo::spec().name);
}
```

```
error[E0425]: cannot find type `Inner` in module `super`
error[E0425]: cannot find type `Local` in module `super`
```

**Cause.** The derive emits its tables inside a generated `mod` and reaches the user's types through `super`. For a type at module scope that is correct. For one declared in a function body it is not: `super` from a module nested in a `fn` resolves to the enclosing *module*, where the function-local types are not visible.

**Scope.** Every derive shape, not one of them — reproduced with a wrapping variant and no unit variant anywhere, and identically with a bare variant. Pre-existing, not introduced by #923.

**Why it matters.** It is a papercut rather than a blocker — a real CLI declares its types at module scope — but it bites tests and examples, which are exactly where a reader tries the derive first, and the error names a generated identifier rather than anything the author wrote.

**Fix direction.** Either emit without a wrapping `mod` (const-scoped items, no `super`), or thread the path in so the generated code refers to the types by a path that is valid from wherever it is emitted. The first is likely simpler and removes the `super` assumption rather than parameterising it.

*AI-assisted — Tool: Claude Code; model: anthropic/claude-opus-5; version: unavailable.*
